apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-username: cm9vdA==
  mysql-password: QXNoaXNoQDg5ODM=
  mail-username: ODJhMDllN2E4NGJkM2EK
  mail-password: ODZlYjczY2I5ZGQ2ODEK